site_name: MKB2
repo_url: https://github.com/Drg95/mkb2
edit_uri: edit/mkdocs/docs/
theme:
  name: material
  language: en
  features:
    - content.action.view
    - content.code.copy
  palette:
    - scheme: preference
    primary: red
    accent: indigo
<<<<<<< HEAD
    toggle:
      icon: material/toggle-switch-off-outline
      name: "Switch to light mode"
  palette:
    - scheme: iceberg
    primary: indigo
    accent: red
    toggle:
      icon: material/toggle-switch
      name: "Switch to dark mode"
=======
  user_color_mode_toggle: true
>>>>>>> 15ea9fdaa016dc9ca9d1675b032a40f86b00842b
plugins:
  - blog:
      blog_dir: blog
  - glightbox:
      auto_caption: true
  - offline
  - search
  - tags
markdown_extensions:
  - pymdownx.extra
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: true
      linenums: true
      use_pygments: true
  - pymdownx.magiclink
  - pymdownx.tasklist
